### ISSUE TITLE
Problem accessing the binary files with Windows

### ISSUE THREAD

**Issue by crigouzzo** [wevbarker/HiGGS#1] opened 2022-08-08 10:09 UTC
<img width="913" alt="image" src="https://user-images.githubusercontent.com/28714994/183394406-346b4702-0754-425c-941a-a98283e7808a.png">
Hi, 

There seems to be an issue accessing binary files with Windows. Probably linked to the IfBuild command in HiGGS_source.nb

**Comment by wevbarker** [comment] 2022-09-05 19:42
Hi!

This was caused by Windows using backslash in path.
Hopefully fixed in [v 1.2.3](https://github.com/wevbarker/HiGGS/commit/bafc37704e99f2e7ea0f3bc451658e0a3f5f2c42).

**Closed as completed by wevbarker** 2022-09-05 19:42 UTC
